version: "3.9"

services:
  claude-blank-dev-env:
    container_name: ${COMPOSE_PROJECT_NAME}
    hostname: ${COMPOSE_PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile.claude
      args:
        ERLANG_VERSION: ${ERLANG_VERSION}
        ELIXIR_VERSION: ${ELIXIR_VERSION}
        ELIXIR_FULL_VERSION: ${ELIXIR_FULL_VERSION}
        KERL_CONFIGURE_OPTIONS: ${KERL_CONFIGURE_OPTIONS}
    environment:
      - CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
      - CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1
      - CLAUDE_CODE_EFFORT_LEVEL=high
      - DISABLE_ERROR_REPORTING=1
      - DISABLE_TELEMETRY=1
      - USE_BUILTIN_RIPGREP=0
      - IS_SANDBOX=1
      - ERLANG_VERSION=${ERLANG_VERSION}
      - ELIXIR_VERSION=${ELIXIR_VERSION}
      - ELIXIR_FULL_VERSION=${ELIXIR_FULL_VERSION}
      - KERL_CONFIGURE_OPTIONS=${KERL_CONFIGURE_OPTIONS}
      - CLAUDE_ENV_FILE=/root/load-project-env.sh
    volumes:
      - ./.claude:/root/.claude
      - ./.claude.json:/root/.claude.json
      - ./.claude.json.backup:/root/.claude.json.backup
      - ./.vim:/root/.vim
      - ./.vimrc:/root/.vimrc
      - ./projects:/root/projects
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh_keys:/root/.ssh
    working_dir: /root/projects
    stdin_open: true
    tty: true
    ports:
      - "${SSH_HOST_PORT:-3222}:3222"
#    command: ["bash", "-l"]
    command: ["bash", "-c", "source /root/erlang/OTP-${ERLANG_VERSION}/activate && source /root/.kiex/elixirs/elixir-${ELIXIR_FULL_VERSION}.env && ~/.local/bin/claude update && ~/.local/bin/claude --dangerously-skip-permissions"]

volumes:
  ssh_keys:
